// Code generated by sqlc. DO NOT EDIT.

package racl_repo

import (
	"database/sql"

	"github.com/google/uuid"
)

type RaclAcl struct {
	ID           uuid.UUID    `json:"id"`
	CreatedAt    sql.NullTime `json:"createdAt"`
	UpdatedAt    sql.NullTime `json:"updatedAt"`
	ResourceID   string       `json:"resourceID"`
	Entity       string       `json:"entity"`
	Capabilities []string     `json:"capabilities"`
}

type RaclResource struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type RaclUser struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	Name      string       `json:"name"`
	ApiKey    string       `json:"apiKey"`
	ApiSecret string       `json:"apiSecret"`
}
