// Code generated by sqlc. DO NOT EDIT.
// source: racl_users.sql

package racl_repo

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO racl_users (
  name, api_key, api_secret
) VALUES (
  $1, $2, $3
) RETURNING id, created_at, updated_at, name, api_key, api_secret
`

type CreateUserParams struct {
	Name      string `json:"name"`
	ApiKey    string `json:"apiKey"`
	ApiSecret string `json:"apiSecret"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (RaclUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.ApiKey, arg.ApiSecret)
	var i RaclUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ApiKey,
		&i.ApiSecret,
	)
	return i, err
}
